### ISSUE TITLE
Archive of Parla is broken

### ISSUE THREAD

**Issue by Kirtai** [kyle-github/littlesmalltalk#2]
The archive parla-3.05p7.tar.gz seems to be a gzipped copy of the Wayback Machine web page, not the tar file it should be.

I've searched but haven't been able to find a copy anywhere else.

**Comment by kyle-github** [comment]
Thanks for bringing this up.  I will hunt around to see if I can find another copy.   It looks like Charles Childer's Littlesmalltalk repo does not have it either.

**Comment by kyle-github** [comment]
I am not seeing any copies now.  The one from the Wayback Machine is definitely wrong.   I will need to remove this until another good copy is found.

**Comment by kyle-github** [comment]
I removed Parla from the archive and updated the README.
