### ISSUE TITLE
Some small enhancements

### ISSUE THREAD

**Issue by SamSandq** [kyle-github/littlesmalltalk#5]
I've added two enhancements to my system to make lst more compatible with 'standard' Smalltalk:

1) modified the Parser method with support for assignment with := in addition to <-
 
tokenIsArrow
    (token isKindOf: String) ifFalse: [ ^ false ].
    ^ token = '<-' or: [token = ':=']

I could not verify that the corresponding modification to bootstrap.c:

line 1594:

       if ((*p == '<') && (*(p + 1) == '-') ||
            (*p == ':') && (*(p + 1) == '=')) {         //SSQ+
 
is enough to affect the same to the initial image creation. Could you please comment?

2) added the following method to String to support standard string concatenation with comma;

, arg
     ^ (self + arg)

**Comment by kyle-github** [comment]
This looks pretty close.   I'll try to make this a change in the next few days.

**Comment by kyle-github** [comment]
I just checked this into my current dev branch.  Thanks for pointing this out and providing the fixes!

**Comment by kyle-github** [comment]
Released as v4.7.2.
